# Generated by Django 3.2.10 on 2023-05-10 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('tail_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('time_zone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_num', models.CharField(max_length=20)),
                ('num_ticket', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
                ('passport_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('web_address', models.CharField(max_length=100)),
                ('airline_login_name', models.CharField(max_length=100)),
                ('airline_login_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PassengersBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline2.bookings')),
                ('passengers_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline2.passengers')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=20)),
                ('booking_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('stamp', models.CharField(max_length=20)),
                ('payment_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline2.paymentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField(default=datetime.datetime.now)),
                ('date', models.DateField(auto_now=True)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('aircraft', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline2.aircraft')),
                ('arrival_airport', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airline2.airports')),
                ('departure_airport', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airline2.airports')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='flight_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline2.flight'),
        ),
    ]
