# Generated by Django 3.2.10 on 2023-05-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_company',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='flight_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline1.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline1.aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airline1.airports'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airline1.airports'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='booking_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline1.bookings'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='payment_provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline1.paymentprovider'),
        ),
        migrations.AlterField(
            model_name='passengersbookings',
            name='booking_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline1.bookings'),
        ),
        migrations.AlterField(
            model_name='passengersbookings',
            name='passengers_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airline1.passengers'),
        ),
    ]
