# Generated by Django 3.2.10 on 2023-05-11 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline1', '0002_auto_20230511_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='seats_number',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='seat_class',
            field=models.CharField(default='Business', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_capcity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_number',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='second_class_capcity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='second_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='third_class_capcity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='third_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='passengers',
            name='email',
            field=models.CharField(default='123@qq.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_num',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_company',
            field=models.CharField(default='ceair', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_num',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_num',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='passport_num',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
